#!/bin/bash

# computers=('allemagne' 'angleterre' 'autriche' 'belgique' 'espagne' 'finlande' 'france' 'groenland' 'hollande' 'hongrie' 'irlande' 'islande' 'lituanie' 'malte' 'monaco' 'pologne' 'portugal' 'roumanie' 'suede' 'albatros' 'autruche' 'bengali' 'coucou' 'dindon' 'epervier' 'faisan' 'gelinotte' 'hibou' 'harpie' 'jabiru' 'kamiche' 'linotte' 'loriol' 'mouette' 'nandou' 'perdrix' 'quetzal' 'quiscale' 'rouloul' 'sitelle' 'traquet' 'urabu' 'verdier' 'aerides' 'barlia' 'calanthe' 'diuris' 'encyclia' 'epipactis' 'gennaria' 'habenaria' 'isotria' 'ipsea' 'liparis' 'lycaste' 'malaxis' 'neotinea' 'oncidium' 'ophrys' 'orchis' 'pleione' 'pogonia' 'serapias' 'telipogon' 'vanda' 'vanilla' 'xylobium' 'zeuxine' 'ain' 'allier' 'ardennes' 'carmor' 'charente' 'cher' 'creuse' 'dordogne' 'doubs' 'essonne' 'finistere' 'gironde' 'indre' 'jura' 'landes' 'loire' 'manche' 'marne' 'mayenne' 'morbihan' 'moselle' 'saone' 'somme' 'vendee' 'vosges' 'ablette' 'anchois' 'anguille' 'barbeau' 'barbue' 'baudroie' 'brochet' 'carrelet' 'gardon' 'gymnote' 'labre' 'lieu' 'lotte' 'mulet' 'murene' 'piranha' 'raie' 'requin' 'rouget' 'roussette' 'saumon' 'silure' 'sole' 'thon' 'truite' 'acromion' 'apophyse' 'astragale' 'atlas' 'axis' 'coccyx' 'cote' 'cubitus' 'cuboide' 'femur' 'frontal' 'humerus' 'malleole' 'metacarpe' 'parietal' 'perone' 'phalange' 'radius' 'rotule' 'sacrum' 'sternum' 'tarse' 'temporal' 'tibia' 'xiphoide' 'bentley' 'bugatti' 'cadillac' 'chrysler' 'corvette' 'ferrari' 'fiat' 'ford' 'jaguar' 'lada' 'maserati' 'mazda' 'nissan' 'niva' 'peugeot' 'pontiac' 'porsche' 'renault' 'rolls' 'rover' 'royce' 'simca' 'skoda' 'venturi' 'volvo')
computers=('albatros' 'autruche' 'bengali' 'coucou' 'dindon' 'epervier' 'faisan' 'gelinotte' 'hibou' 'harpie' 'jabiru' 'kamiche' 'linotte' 'loriol' 'mouette' 'nandou' 'perdrix' 'quetzal' 'quiscale' 'rouloul' 'sitelle' 'traquet' 'urabu' 'verdier' 'malleole')

for computer in "${computers[@]}"
do  
	gnome-terminal --tab -- ssh guilherme.vieira-manhaes@$computer.polytechnique.fr "./run_models.sh";
done
